CREATE VIEW MI181_CPMANING.Hot_emp_view
(EMP_FNAME,EMP_LNAME,ID)
AS
SELECT MI181_CPMANING.employee.emp_fname,
    MI181_CPMANING.employee.emp_lname,
    MI181_CPMANING.hotel.id
   FROM (MI181_CPMANING.employee
     LEFT JOIN MI181_CPMANING.hotel ON ((MI181_CPMANING.employee.id = MI181_CPMANING.hotel.id)))

CREATE VIEW MI181_CPMANING.CUSTOMER_ROOM_view
(CUS_FNAME,CUS_LNAME,ID)
AS
SELECT MI181_CPMANING.customer.cus_fname,
    MI181_CPMANING.customer.cus_lname,
    MI181_CPMANING.room.id
   FROM (MI181_CPMANING.customer
     LEFT JOIN MI181_CPMANING.room ON ((MI181_CPMANING.CUSTOMER.id = MI181_CPMANING.room.id)))
     